# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: "3.11"
       - name: Install dependencies
         run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
            
       - name: Write secret to .env
         run: echo "TISSO_API_KEY=${{ secrets.API_KEY_TISSEO }}" > .env
  
       - name: Display .env content (for debug purposes only; remove in production!)
         run: cat .env
         env:
            TISSO_API_KEY: ${{ secrets.API_KEY_TISSEO }}
  
       - name: Run mock script
         env:
           TISSO_API_KEY: ${{ secrets.API_KEY_TISSEO }}
         run: |
            python -c "import os
            print(f'Token from env: {os.environ.get(\"TISSO_API_KEY\")}')"


       - name: Setting up API Key secrets and mock test
         env:
           TISSO_API_KEY : ${{ secrets.API_KEY_TISSEO }}
         run: python mock_test.py
